# Generated by Django 5.2 on 2025-06-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_livro_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editora',
            old_name='dnome',
            new_name='nome',
        ),
    ]
