# Generated by Django 5.2 on 2025-06-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_autor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
