# Generated by Django 5.2 on 2025-06-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_editora_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
