# Generated by Django 5.2.2 on 2025-09-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_itenscompra_preco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itenscompra',
            options={'verbose_name': 'Item de Compra', 'verbose_name_plural': 'Itens de Compra'},
        ),
        migrations.AlterUniqueTogether(
            name='itenscompra',
            unique_together={('compra', 'livro')},
        ),
    ]
